from io import BytesIO
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph


def generate_pdf(evaluation_data):
    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    elements = []

    elements.append(Paragraph("<b>AI Startup Idea Validator</b>", styles["Title"]))

    elements.append(Paragraph("<br/>", styles["Normal"]))

    elements.append(
        Paragraph(
            f"<b>Startup Idea:</b> {evaluation_data['startup_idea']}",
            styles["Heading2"]
        )
    )

    categories = [
        "creativity",
        "demand",
        "uniqueness",
        "scale",
        "investment"
    ]

    total = 0

    for cat in categories:

        score = evaluation_data[f"{cat}_score"]
        sentence = evaluation_data[f"{cat}_sentence"]

        total += score

        elements.append(
            Paragraph(
                f"<b>{cat.title()}</b> ({score}/10)",
                styles["Heading3"]
            )
        )

        elements.append(
            Paragraph(sentence, styles["BodyText"])
        )

    overall = total / len(categories)

    elements.append(Paragraph("<br/>", styles["Normal"]))

    elements.append(
        Paragraph(
            f"<b>Overall Score:</b> {overall:.1f}/10",
            styles["Heading2"]
        )
    )
    elements.append(
    Paragraph(
        "<font size=9 color='grey'><i>Generated by AI Startup Idea Validator • Made by DG</i></font>"
       
    )
)
    doc.build(elements)

    buffer.seek(0)

    return buffer